name: Build and Push Docker Images

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push API Gateway
        run: |
          cd api-gateway
          mvn clean package -DskipTests
          docker build -t $DOCKER_USERNAME/api-gateway:latest .
          docker push $DOCKER_USERNAME/api-gateway:latest

      - name: Build & Push Discovery Service
        run: |
          cd discovery-service
          mvn clean package -DskipTests
          docker build -t $DOCKER_USERNAME/discovery-service:latest .
          docker push $DOCKER_USERNAME/discovery-service:latest

      - name: Build & Push Product Service
        run: |
          cd product-service
          mvn clean package -DskipTests
          docker build -t $DOCKER_USERNAME/product-service:latest .
          docker push $DOCKER_USERNAME/product-service:latest

      - name: Build & Push Order Service
        run: |
          cd order-service
          mvn clean package -DskipTests
          docker build -t $DOCKER_USERNAME/order-service:latest .
          docker push $DOCKER_USERNAME/order-service:latest

      - name: Build & Push Inventory Service
        run: |
          cd inventory-service
          mvn clean package -DskipTests
          docker build -t $DOCKER_USERNAME/inventory-service:latest .
          docker push $DOCKER_USERNAME/inventory-service:latest

      - name: Build & Push Notification Service
        run: |
          cd notification-service
          mvn clean package -DskipTests
          docker build -t $DOCKER_USERNAME/notification-service:latest .
          docker push $DOCKER_USERNAME/notification-service:latest
